# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1330f8b9ec8dd97f1782594a1a59484a834e5b3c3b3a85ad69d204fd0554a4cfef0817a58d3acf7d85a64c7168824276fbaf9cb70a5b753fbfe97ca077595a4f

test:
  secret_key_base: ac951eef3952bbc1c4dd392dbe4fc8e2ff321b29a0656fd888a148f11392a567d57f5f79112749cfa0a3bab54c12384844844c4da0d8d7ff73f95025fe644831

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
